# Generated by Django 5.0.2 on 2024-03-19 14:29
# added comments to make this file visible

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productype',
            new_name='producttype',
        ),
    ]
