# Generated by Django 5.0.2 on 2024-05-05 14:35

import django.core.validators
import django.db.models.deletion
import merchstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_rename_productype_product_producttype'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('SALE', 'On Sale'), ('AVAIL', 'Available')], default=merchstore.models.stockstate, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Number of stock should be nonnegative!')]),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Amount should not be empty!')])),
                ('status', models.CharField(choices=[('CRT', 'On Cart'), ('PAY', 'To Pay'), ('SHIP', 'To Ship'), ('RECEIVE', 'To Receive'), ('DELIVER', 'Delivered')], max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchstore.product')),
            ],
        ),
    ]
