# Generated by Django 5.0.2 on 2024-05-07 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_product_owner_product_status_product_stock_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('SALE', 'On Sale'), ('AVAIL', 'Available'), ('EMPTY', 'Out of Stock')], max_length=255),
        ),
    ]
