# Generated by Django 5.0.2 on 2024-05-08 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_alter_product_owner_alter_product_status'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Number of stock should be nonnegative!')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Amount should not be empty!')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('CRT', 'On Cart'), ('PAY', 'To Pay'), ('SHIP', 'To Ship'), ('RECEIVE', 'To Receive'), ('DELIVER', 'Delivered')], max_length=64),
        ),
    ]
