# Generated by Django 5.0.3 on 2024-05-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['status', '-created_on']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['status', '-applied_on']},
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Full')], default=1),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1, max_length=8),
        ),
    ]
