# Generated by Django 5.0.3 on 2024-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commission_description_commission_people_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
