# Generated by Django 5.0.3 on 2024-05-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='people_required',
        ),
    ]
