# Generated by Django 5.0.4 on 2024-04-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_comment_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
